### ISSUE TITLE
Wrong finnish word usage 

### ISSUE THREAD

**Issue by FirePlank** [Muhimen123/TID#2]
We finnish people use "taustakuva" for discussing desktop wallpapers and not "tapetti". Also I didn't know you were active again on Github and I'm glad you are back 😃

**Comment by classPythonAddike** [comment]
![image](https://user-images.githubusercontent.com/72556571/126477295-43f35029-85b1-4826-8f8b-c1deacaba80e.png)
![image](https://user-images.githubusercontent.com/72556571/126477323-52da66b5-dfe5-4b35-96b6-b2ca2680c0b7.png)
Both look correct :smilecat:

**Comment by FirePlank** [comment]
the wallpaper is meant as in a wallpaper in real life and it says right there that taustakuva is a (computing) background image :uganda:

**Comment by classPythonAddike** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm :thinking:

**Comment by FirePlank** [comment]
no one ever uses tapetti for the wording of a desktop wallpaper i quarentee you that lmao

**Comment by Shiv-Patil** [comment]
Yes but the latter is more correct according to [this](https://www.tomorrowtides.com/tappeti-vs-taustakuva.html) website

**Comment by FirePlank** [comment]
bruh i fell for it

**Comment by classPythonAddike** [comment]
lmao

**Comment by classPythonAddike** [comment]
> bruh i fell for it

If you want another one, there's one in the readme :wink:

**Comment by Martian-dev** [comment]
HELLO THERE!!

**Comment by Shiv-Patil** [comment]
Hello Martian

**Comment by FirePlank** [comment]
lol hi

**Comment by Muhimen123** [comment]
> no one ever uses tapetti for the wording of a desktop wallpaper i quarentee you that lmao

Yeah, says you

**Comment by Muhimen123** [comment]
![image](https://user-images.githubusercontent.com/44261822/126522609-207c247e-72f1-4917-8def-3eabe9a6e0a9.png)

**Comment by Martian-dev** [comment]
@Muhimen123 why did you delete your discord account 😢

**Comment by Martian-dev** [comment]
We missed you man

**Comment by Muhimen123** [comment]
> > bruh i fell for it
> 
> If you want another one, there's one in the readme 😉

You fell for it? :mhm:

Might change it tho since the Tapetti do exist now

**Comment by Martian-dev** [comment]
_ignores me_

**Comment by Muhimen123** [comment]
> @Muhimen123 why did you delete your discord account 😢

*existential crisis* you might say

**Comment by Martian-dev** [comment]
What does that mean??
:peep:

**Comment by FirePlank** [comment]
saykat come back to discord and also the correct word is taustakuva like it or not

**Comment by classPythonAddike** [comment]
So is the name going to be `tapetti` or `taustakuva` :peep:

**Comment by classPythonAddike** [comment]
Also, could we have a gui for tapetti/taustakuva :eyes:

**Comment by Muhimen123** [comment]
Well, `tapetti` it was, `tapetti` it is, `tapetti` it will. 

Reasons:
 - taustakuva is a bit mouthful
 - doesn't sound as good as tapetti
 - tapetti is easy to use
 - tapetti sounds kina cute as well(imo)
 - tapetti is easy to remember 
 - not all of us are Finnish

**Comment by Muhimen123** [comment]
> Also, could we have a gui for tapetti/taustakuva 👀

I have a plan to make a website(prolly github page) for TID.
and a gui for the `view` command of Tapetti.

**Comment by FirePlank** [comment]
Tapetti sounds cute? Lol. It should be an pretty easy change tho since both start with t so to don't have to change any of your shortening like tid

**Comment by Muhimen123** [comment]
Nah, Tapetti is better.

**Comment by Martian-dev** [comment]
Yo SAYKAT

**Comment by classPythonAddike** [comment]
:mhmf:

**Comment by FirePlank** [comment]
Dead issue
