### ISSUE TITLE
GUI, Website for tapetti

### ISSUE THREAD

**Issue by classPythonAddike** [Muhimen123/TID#3]
> > Also, could we have a gui for tapetti/taustakuva :eyes:
>
> I have a plan to make a website(prolly github page) for TID.
> and a gui for the view command of Tapetti.

When does work on it start? :smilecat: I can contribute in a week or so, exams are nearly over :dorime:

**Comment by FirePlank** [comment]
Bun__

**Comment by Shiv-Patil** [comment]
Bunned?

**Comment by classPythonAddike** [comment]
<img src="https://cdn.discordapp.com/emojis/804897507602857985.gif?v=1">

**Comment by FirePlank** [comment]
https://jklm.fun/EMHD

**Comment by Shiv-Patil** [comment]
![image](https://user-images.githubusercontent.com/35653831/130435381-1204caf4-262d-4536-aa02-99bd4ab0e255.png)

**Comment by classPythonAddike** [comment]
<img src="https://cdn.discordapp.com/emojis/862241549340508190.gif?v=1">

**Comment by classPythonAddike** [comment]
> https://jklm.fun/EMHD

<img src="https://cdn.discordapp.com/emojis/847469236132511784.png?v=1">

**Comment by DemiGod108** [comment]
What is this

**Comment by Muhimen123** [comment]
> > > Also, could we have a gui for tapetti/taustakuva eyes
> > 
> > 
> > I have a plan to make a website(prolly github page) for TID.
> > and a gui for the view command of Tapetti.
> 
> When does work on it start? :smilecat: I can contribute in a week or so, exams are nearly over :dorime:

Probably in the beginning of the next month. I have exams as well. Stuck until 31st this month.

**Comment by classPythonAddike** [comment]
ok :dorime:
